#pragma once

enum ENUM_SETTING
{
    SETTING_UNKNOWN = -1,
    SETTING_PARENT_ID,
    SETTING_SESSION_ID,
    SETTING_CPU_USAGE,
    SETTING_MEMORY_USAGE,
    SETTING_HANDLE_COUND,
    SETTING_CREATE_TIME,
    SETTING_USER_COUNT,
    SETTING_GDI_COUNT,
    SETTING_PROCESS_PATH,
    SETTING_END,
};