#pragma once

enum ENUM_SETTING
{
    SETTING_UNKNOWN = -1,
    SETTING_CPU_USAGE,
    SETTING_MEMORY_USAGE,
    SETTING_PROCESS_PATH,
    SETTING_THREAD_COUNT,
    SETTING_HANDLE_COUND,
    SETTING_PARENT_THREAD,
    SETTING_OTHER_1,
    SETTING_OTHER_2,
    SETTING_END,
};